steps:
  - name: "hashicorp/terraform:1.0.0"
    args: ["init"]

  - name: "hashicorp/terraform:1.0.0"
    args: ["apply", "-auto-approve"]

  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/thelooneytoons-tasks/python-image:new", "."]

  # Docker Push
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/thelooneytoons-tasks/python-image:new"]

  - name: gcr.io/cloud-builders/kubectl
    args:
      - cluster-info
    env:
      - CLOUDSDK_COMPUTE_ZONE=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

  - name: gcr.io/$PROJECT_ID/helm
    args:
      - upgrade
      - -i
      - my-app
      - ./kubernetes
      - -f
      - ./kubernetes/values.yaml
    env:
      - KUBECONFIG=/workspace/.kube/config
      - TILLERLESS=false
      - TILLER_NAMESPACE=kube-system

  # - name: "gcr.io/cloud-builders/kubect"
  #   args:
  #     - "run"
  #     - "gke-cluster"
  #     - "--image=gcr.io/thelooneytoons-tasks/python-image:v1"
  #     - "--port=8080"

timeout: 1000s
substitutions:
  _CUSTOM_REGION: us-central1-c
  _CUSTOM_CLUSTER: gke-cluster

options:
  logging: CLOUD_LOGGING_ONLY
# kubectl run -it --rm busybox-1321-run --image=gcr.io/$project_id/busybox:1.32.1 -n default -- sh

# images:
# - "gcr.io/thelooneytoons-tasks/python-image:v1"
