---
version: "3"

services:
  my_app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./connect.py:/usr/src/app/connect.py
    environment:
      NODE_ENV: development
      PORT: "3000"
